fix bug in release pipeline

diff --git a/.github/workflows/deploy-stage.yaml b/.github/workflows/deploy-stage.yaml
--- a/.github/workflows/deploy-stage.yaml
+++ b/.github/workflows/deploy-stage.yaml
@@ -165,6 +165,7 @@ jobs:
       - name: generate CLI manifest
         run: |
           set -evo pipefail
+          trap 'echo "Error occurred at line $LINENO: $BASH_COMMAND";' ERR
           ROOT="$(pwd)"
 
           export CLI_VERSION="$GITHUB_REF_NAME"
@@ -253,6 +254,7 @@ jobs:
       - name: create cli-plugins-index PR
         run: |
           set -evo pipefail
+          trap 'echo "Error occurred at line $LINENO: $BASH_COMMAND";' ERR
           ROOT="$(pwd)"
 
           # we assume GITHUB_REF_NAME is the version number prefixed with `v`. This is checked in previous steps
@@ -313,6 +315,7 @@ jobs:
       - name: create ndc-hub PR
         run: |
           set -evo pipefail
+          trap 'echo "Error occurred at line $LINENO: $BASH_COMMAND";' ERR
           ROOT="$(pwd)"
 
           # we assume GITHUB_REF_NAME is the version number prefixed with `v`. This is checked in previous steps
@@ -334,7 +337,7 @@ jobs:
           git checkout -b $BRANCH_NAME
 
           # create new connector definition
-          mkdir "${ROOT}/ndc-hub/registry/hasura/clickhouse/releases/v$RELEASE_VERSION"
+          mkdir "${ROOT}/ndc-hub/registry/hasura/clickhouse/releases/$RELEASE_VERSION"
           cat "${ROOT}/ndc-clickhouse/ci/templates/connector-packaging.json" | envsubst > "${ROOT}/ndc-hub/registry/hasura/clickhouse/releases/$RELEASE_VERSION/connector-packaging.json"
 
           # modify metadata file to add new entry
