add better logging for bash scripts

diff --git a/.github/workflows/deploy-stage.yaml b/.github/workflows/deploy-stage.yaml
--- a/.github/workflows/deploy-stage.yaml
+++ b/.github/workflows/deploy-stage.yaml
@@ -105,6 +105,9 @@ jobs:
 
       - name: build the CLI
         run: |
+          set -evo pipefail
+          trap 'echo "Error occurred at line $LINENO: $BASH_COMMAND";' ERR
+
           # If we're on a tag, use the tag name as the release version.
           if [[ "$GITHUB_REF_TYPE" == 'tag' ]]; then
             # Ensure that the version specified in Cargo.toml is the same as the tag (with a 'v' prefix).
diff --git a/.github/workflows/tag-release.yaml b/.github/workflows/tag-release.yaml
--- a/.github/workflows/tag-release.yaml
+++ b/.github/workflows/tag-release.yaml
@@ -26,6 +26,9 @@ jobs:
     - name: Read version from Cargo.toml and push appropriate tag
       id: read-version
       run: |
+        set -evo pipefail
+        trap 'echo "Error occurred at line $LINENO: $BASH_COMMAND";' ERR
+
         CARGO_VERSION="$(cargo metadata --format-version=1 | jq -r '.packages | .[] | select(.name == "ndc-clickhouse-cli") | .version')"
         VERSION_TAG="v$CARGO_VERSION"
         if git rev-parse "$VERSION_TAG" >/dev/null 2>&1; then
